# Generated by Django 4.2.4 on 2023-08-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('Purpose', models.CharField(max_length=100)),
                ('Dropdown', models.CharField(max_length=100)),
                ('Dropdownsecond', models.CharField(max_length=100)),
            ],
        ),
    ]
