# Generated by Django 4.2.4 on 2023-08-14 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Dropdown',
            new_name='SelectDate',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Dropdownsecond',
            new_name='SelectSlot',
        ),
    ]
