# Generated by Django 4.2.4 on 2023-08-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_dropdown_contact_selectdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='SelectDate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
