# Generated by Django 4.2.4 on 2023-08-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_contact_selectslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='SelectDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='SelectSlot',
            field=models.TimeField(null=True),
        ),
    ]
