# Generated by Django 4.2.4 on 2023-08-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_contact_selectdate_alter_contact_selectslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='SelectDate',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='SelectSlot',
        ),
    ]
