# Generated by Django 4.2.4 on 2023-08-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_selectdate_contact_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Date',
            new_name='SelectDate',
        ),
    ]
