# Generated by Django 4.2.4 on 2023-08-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_contact_selectslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Purpose',
            new_name='purpose',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='SelectDate',
            new_name='selected_date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='SelectSlot',
            new_name='selected_slot',
        ),
    ]
