# Generated by Django 4.2.4 on 2023-08-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_email_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('parashap', models.CharField(max_length=100)),
            ],
        ),
    ]
