# Generated by Django 4.2.4 on 2023-08-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('parashap', models.CharField(max_length=100)),
            ],
        ),
    ]
