# Generated by Django 4.2.4 on 2023-08-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Gallery1',
        ),
    ]
