# Generated by Django 4.2.4 on 2023-08-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_rename_gallery_gallery1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('parashpa', models.CharField(max_length=100)),
            ],
        ),
    ]
