# Generated by Django 4.2.4 on 2023-08-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_contacts_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Topics',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
