# Generated by Django 4.2.4 on 2023-08-16 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_contacts_message_alter_contacts_topics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Update',
        ),
    ]
