# Generated by Django 4.2.4 on 2023-08-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_rename_blog_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sector',
            new_name='Business',
        ),
        migrations.RenameModel(
            old_name='Gallery1',
            new_name='Gallery_image',
        ),
    ]
