# Generated by Django 4.2.4 on 2023-08-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_rename_sector_business_rename_gallery1_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='Fullname',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='Message',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='Topics',
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='fullname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='topics',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
