# Generated by Django 4.2.4 on 2023-08-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_remove_contacts_email_remove_contacts_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='icon',
            field=models.CharField(choices=[('bi-app-indicator', 'Mobile Apps'), ('bi-pie-chart', 'Digital Content'), ('bi-tools', 'WordPress 5.0')], default=12, max_length=20),
            preserve_default=False,
        ),
    ]
