# Generated by Django 4.2.4 on 2023-08-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_business_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='icon',
            field=models.CharField(choices=[('bi-cup', 'WordPress'), ('bi-star-half', 'Frontend Solution'), ('bi-geo-alt', 'Live Chat Help'), ('bi-graph-up', 'Frontend')], default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='icon',
            field=models.CharField(choices=[('bi-app-indicator', 'Mobile Apps'), ('bi-pie-chart', 'Digital Content'), ('bi-tools', 'WordPress 5.0'), ('bi-sun', 'Business Idea')], max_length=20),
        ),
    ]
