# Generated by Django 4.2.4 on 2023-08-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_about_icon_alter_business_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('bi-gear', 'Boot your sales'), ('bi-pie-chart', 'Branding'), ('bi-whatsapp', 'Live Chat Help')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('parashpa', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
