# Generated by Django 4.2.4 on 2023-08-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_awards_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='icon',
            field=models.CharField(choices=[('bi-gear', 'Boot your sales'), ('bi-cursor', 'WordPress'), ('bi-whatsapp', 'Live Chat Help')], max_length=20),
        ),
    ]
