# Generated by Django 4.2.4 on 2023-08-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_alter_awards_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='icon',
            field=models.CharField(choices=[('bi-app-indicator', 'Mobile Apps'), ('bi-gear', 'Branding'), ('bi-tools', 'WordPress 5.0'), ('bi-pie-chart', 'Digital')], max_length=20),
        ),
    ]
