# Generated by Django 4.2.4 on 2023-08-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_update_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_portfolio_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('topics', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
