# Generated by Django 4.2.4 on 2023-08-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
