# Generated by Django 4.2.4 on 2023-08-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
