# Generated by Django 4.2.4 on 2023-08-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_alter_email_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
