# Generated by Django 4.2.4 on 2023-08-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_alter_email_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
