# Generated by Django 4.2.4 on 2023-08-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='blog_form_one',
        ),
        migrations.DeleteModel(
            name='blog_form_three',
        ),
        migrations.DeleteModel(
            name='blog_form_two',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
