# Generated by Django 4.2.4 on 2023-08-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_tag_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogblog',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
