# Generated by Django 4.2.4 on 2023-08-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_alter_business_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='icon',
            field=models.CharField(choices=[('bi-app-indicator', 'Mobile Apps'), ('bi-pie-chart', 'Digital Content'), ('bi-tools', 'WordPress 5.0'), ('bi-sun', 'Business Idea')], max_length=20),
        ),
    ]
