# Generated by Django 4.2.4 on 2023-08-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_alter_business_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='icon',
            field=models.CharField(choices=[('bi-app-indicator', 'Mobile Apps'), ('bi-gear', 'Branding'), ('bi-tools', 'WordPress 5.0'), ('bi-pie-chart', 'Digital'), ('bi-geo-alt', 'Branding'), ('bi-graph-up', 'Frontend'), ('bi-whatsapp', 'Live Chat Help')], max_length=20),
        ),
    ]
