# Generated by Django 4.2.4 on 2023-08-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_alter_awards_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='icon',
            field=models.CharField(choices=[('bi-cup', 'WordPress'), ('bi-star-half', 'Frontend Solution'), ('bi-geo-alt', 'Live Chat Help'), ('bi-graph-up', 'Frontend'), ('bi-pie-chart', 'Digital'), ('bi-geo-alt', 'Branding'), ('bi-graph-up', 'Frontend'), ('bi-whatsapp', 'Live Chat Help')], max_length=20),
        ),
    ]
